# Load, Display, Resize and Write Image

In [ ]:
#Import OpenCV library
import cv2

In [3]:
#Read the image - imread takes two parameters
# 1) Image location and name
# 2) Color scale - 0 --> B&W(grey scale) or 1 --> RGB (coloured) or -1 --> HSV(coloured)
img = cv2.imread("galaxy.jpg",0)

In [4]:
#Check the type of image - The image is stored in Matrix form
print(type(img))

<class 'numpy.ndarray'>


In [5]:
#Print the matrix/array of the image
print(img)

[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]


In [6]:
#check the shape of image array
print(img.shape)

(1485, 990)


In [7]:
#Show the actual image
cv2.imshow("Galaxy",img)
#define a waitkey - which displays the image for specified milliseconds.
cv2.waitKey(0)
#Let user close the window by pressing any key
cv2.destroyAllWindows()

In [8]:
#Resizing the image - Remember to put extension with your file name while writing
#resize_img = cv2.resize(img,(500,1000))
resize_img = cv2.resize(img,(int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("Galaxy",resize_img)
cv2.imwrite("Galaxy_resized.jpg",resize_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Batch image resizing

In [9]:
import cv2
import glob

images=glob.glob(r"C:\Users\Natasha Sharma\Documents\sample-images\*.jpg")

for image in images:
    img=cv2.imread(image,0)
    re=cv2.resize(img,(100,100))
    cv2.imshow("resize_image",re)
    cv2.waitKey(500)
    cv2.destroyAllWindows()
    cv2.imwrite("resized_"+image,re)